services:
  - type: web
    name: phd-portfolio-frassi
    runtime: static
    buildCommand: "echo no build step required"
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex, nofollow
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
